### PR TITLE
Add tea.xyz to other products

### PR DESCRIPTION
**Pull request by jacob-willden**
According to [Tea's documentation](https://docs.tea.xyz/features/developer-environments), it can will automatically add the correct version of Node to a project using the `.node-version` file.

### CODE REVIEW

**Comment by shadowspawn** [comment]
Thanks for the link. I think tea belongs with the node version managers, and should have a row in the compatibility table.

If you aren't up for the compatibility testing then just move the listing to the node version managers, and I'll merge and check compatibility later.

**Comment by jacob-willden** [comment]
Thanks for the feedback! I've been having trouble testing compatibility on my machine, so I just moved Tea to the Node version managers section for now.

**Comment by shadowspawn** [comment]
Thanks @jacob-willden , and I am interested in having a look anyway. 👍

**Comment by shadowspawn** [comment]
I had a tough time getting things working, but did get a no-eol file working.

I found a bug and reported that line endings not working:
- https://github.com/teaxyz/cli/issues/538
- https://github.com/teaxyz/cli/issues/539

Update: line-endings ok, that was my mistake with manual testing!

**Pull request merged**
